ALTER TABLE users ADD COLUMN pin_remind_browser_notify BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN pin_remind_sound BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN pin_remind_vibrate BOOLEAN NOT NULL DEFAULT FALSE;
